package buildout

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Target represents the packaging format requested by bo.
type Target string

const (
	TargetEXE Target = "exe"
	TargetAPK Target = "apk"
	TargetIPA Target = "ipa"
	TargetDMG Target = "dmg"
	TargetGOE Target = "goe"
)

// Manifest describes the scope of an export.
type Manifest struct {
	Name        string            `json:"name"`
	Mode        string            `json:"mode,omitempty"`
	Output      string            `json:"output"`
	Module      string            `json:"module"`
	Entrypoint  string            `json:"entrypoint"`
	BaseDir     string            `json:"baseDir,omitempty"`
	AgentsDir   string            `json:"agentsDir,omitempty"`
	Runtime     string            `json:"runtime,omitempty"`
	Description string            `json:"description,omitempty"`
	Pages       []string          `json:"pages,omitempty"`
	Paths       []string          `json:"paths,omitempty"`
	Folders     []string          `json:"folders,omitempty"`
	Include     []string          `json:"include,omitempty"`
	Assets      []string          `json:"assets,omitempty"`
	Slices      []PackSlice       `json:"slices,omitempty"`
	Bundles     []PackBundle      `json:"bundles,omitempty"`
	Environment map[string]string `json:"environment,omitempty"`
	Metadata    map[string]string `json:"metadata,omitempty"`
	Bundle      bool              `json:"bundle,omitempty"`
}

// BuildPlan captures what bo is asked to export.
type BuildPlan struct {
	ManifestPath string            `json:"manifest_path"`
	Manifest     Manifest          `json:"manifest"`
	Target       Target            `json:"target"`
	BuildTarget  string            `json:"build_target"`
	ArtifactRoot string            `json:"artifact_root"`
	CreatedAt    string            `json:"created_at"`
	Slice        ExportSlice       `json:"slice,omitempty"`
	Notes        []string          `json:"notes,omitempty"`
}

// BuildResult describes the output generated by bo.
type BuildResult struct {
	ManifestPath string   `json:"manifest_path"`
	Manifest     Manifest `json:"manifest"`
	Target       Target   `json:"target"`
	BuildTarget  string   `json:"build_target"`
	Status       string   `json:"status"`
	Message      string   `json:"message"`
	OutputPath   string   `json:"output_path,omitempty"`
	BundlePath   string   `json:"bundle_path,omitempty"`
	SlicePath    string   `json:"slice_path,omitempty"`
	Artifacts    []string `json:"artifacts,omitempty"`
}

// ParseTarget normalizes the requested format.
func ParseTarget(raw string) (Target, error) {
	switch strings.ToLower(strings.TrimSpace(raw)) {
	case string(TargetEXE):
		return TargetEXE, nil
	case string(TargetAPK):
		return TargetAPK, nil
	case string(TargetIPA):
		return TargetIPA, nil
	case string(TargetDMG):
		return TargetDMG, nil
	case string(TargetGOE):
		return TargetGOE, nil
	default:
		return "", fmt.Errorf("unsupported target %q", raw)
	}
}

// Normalize fills defaults that are safe to infer.
func (m *Manifest) Normalize(sourcePath string) {
	if m.Name == "" {
		m.Name = strings.TrimSuffix(filepath.Base(sourcePath), filepath.Ext(sourcePath))
	}

	if m.Output == "" {
		m.Output = m.Name
	}

	if m.Mode == "" {
		m.Mode = "cs"
	}

	if m.Module == "" {
		m.Module = "."
	}

	if m.Entrypoint == "" {
		m.Entrypoint = m.Module
	}

	if m.BaseDir == "" {
		m.BaseDir = "base"
	}

	if m.AgentsDir == "" {
		m.AgentsDir = "agents"
	}

	if m.Runtime == "" {
		m.Runtime = "go"
	}

	if m.Environment == nil {
		m.Environment = map[string]string{}
	}

	if m.Metadata == nil {
		m.Metadata = map[string]string{}
	}
}

// Validate makes sure the manifest has the minimum export contract.
func (m Manifest) Validate() error {
	if strings.TrimSpace(m.Name) == "" {
		return fmt.Errorf("pack name is required")
	}

	if strings.TrimSpace(m.Output) == "" {
		return fmt.Errorf("pack output is required")
	}

	if m.Mode != "" && m.Mode != "cs" && m.Mode != "sw" {
		return fmt.Errorf("pack mode must be either \"cs\" or \"sw\"")
	}

	if strings.TrimSpace(m.Module) == "" && strings.TrimSpace(m.Entrypoint) == "" {
		return fmt.Errorf("pack must define a module or entrypoint")
	}

	return nil
}

// BuildTarget resolves the package path that go build should compile.
func (m Manifest) BuildTarget() string {
	target := strings.TrimSpace(m.Entrypoint)
	if target == "" {
		target = strings.TrimSpace(m.Module)
	}
	if target == "" {
		return "."
	}

	if strings.HasPrefix(target, "./") || strings.HasPrefix(target, "../") || filepath.IsAbs(target) {
		return target
	}

	if strings.HasPrefix(target, ".") {
		return target
	}

	segments := strings.Split(target, "/")
	if len(segments) > 0 && strings.Contains(segments[0], ".") {
		return target
	}

	return "./" + target
}

// BinaryName returns the output file name for the host platform.
func (m Manifest) BinaryName() string {
	name := m.Output
	if name == "" {
		name = m.Name
	}

	if runtimeGOOS() == "windows" && !strings.HasSuffix(strings.ToLower(name), ".exe") {
		name += ".exe"
	}

	return name
}

// PlannedOutputDir returns the build root for the manifest.
func (m Manifest) PlannedOutputDir(distDir string) string {
	if distDir == "" {
		distDir = "dist"
	}

	return filepath.Join(distDir, m.Output)
}

// Plan creates a normalized build plan for the manifest.
func (m Manifest) Plan(path string, target Target, distDir string) BuildPlan {
	return BuildPlan{
		ManifestPath: path,
		Manifest:     m,
		Target:       target,
		BuildTarget:  m.BuildTarget(),
		ArtifactRoot:  m.PlannedOutputDir(distDir),
		CreatedAt:    nowRFC3339(),
	}
}
